module.exports = {
  mySidebar: [
    'home',
    {
      type: 'category',
      label: 'UtamakePages',
      items: [
        {
          type: 'autogenerated',
          dirName: './utamake-pages', // '.' means the current docs folder
        },
      ],
    },
  ],
};
